### ISSUE TITLE
Wishlist

### ISSUE THREAD

**Issue by iminders** [SnakeHacker/tweb#1]
帐户管理(不知道如果支持权限配置是否方便，用户-模型）
模型管理功能
- stage: dev, backtesting, paper trading, graduate
- 发布模型： 模型通过URI + secret key 提交参数(如百度网盘）,  performance(包含哪些信息还没想好)

模型输出功能
- 输出：graduate模型，可以定期run输出结果

**Comment by SnakeHacker** [comment]
账号管理参见 #3

**Comment by SnakeHacker** [comment]
迁移至 [tweb](https://github.com/tradingAI/tweb)
