### ISSUE TITLE
build docker image

### ISSUE THREAD

**Issue by SnakeHacker** [SnakeHacker/tweb#2]

**Comment by iminders** [comment]
可以提供只用一条命令启动所有服务 docker-compose-starter.yml 吗

**Comment by SnakeHacker** [comment]
> 可以提供只用一条命令启动所有服务 docker-compose-starter.yml 吗

可以 之后提供一个docker-compose.yml

**Comment by SnakeHacker** [comment]
@iminders Done, pushed to master

**Comment by iminders** [comment]
Great job ! @SnakeHacker

**Comment by SnakeHacker** [comment]
@iminders 新增3种启动方式: 
- prod alpine 直接使用编译好的binary
- 本地开发完后在docker中编译启动
- 本地开发模式分别启动前后端
